pj4w/ch07/AddressBook/src/main/java/com/wrox/pj4w/ch07/model/Contact.java
package com.wrox.pj4w.ch07.model;

import java.time.Instant;
import java.time.MonthDay;
import java.util.Date;

public class Contact implements Comparable<Contact> {
    private String firstName;
    private String lastName;
    private String phoneNumber;
    private String address;
    private MonthDay birthDay;
    private Instant dateCreated;

    public Contact() {
    }

    public Contact(String firstName, String lastName, String phoneNumber, String address, MonthDay birthDay, Instant dateCreated) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.birthDay = birthDay;
        this.dateCreated = dateCreated;
    }

    public Date getOldDateCreated() {
        return new Date(this.dateCreated.toEpochMilli());
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public MonthDay getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(MonthDay birthDay) {
        this.birthDay = birthDay;
    }

    public Instant getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Instant dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public int compareTo(Contact o) {
        int last = lastName.compareTo(o.lastName);
        if (last == 0) {
            return firstName.compareTo(o.firstName);
        }
        return last;
    }
}

pj4w/ch07/AddressBook/src/main/java/com/wrox/pj4w/ch07/servlets/ListServlet.java
package com.wrox.pj4w.ch07.servlets;

import com.wrox.pj4w.ch07.model.Contact;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.jsp.jstl.core.Config;
import java.io.IOException;
import java.time.Instant;
import java.time.Month;
import java.time.MonthDay;
import java.util.*;

@WebServlet("/list")
public class ListServlet extends HttpServlet {
    private static final SortedSet<Contact> contacts = new TreeSet<>();

    static {
        contacts.add(new Contact("Jane", "Sanders", "555-1593", "394 E 22nd Ave",
                MonthDay.of(Month.JANUARY, 5),
                Instant.parse("2013-02-01T15:22:23Z")
        ));
        contacts.add(new Contact( "John", "Smith", "555-0712", "315 Maple St",
                null, Instant.parse("2012-10-15T09:31:17Z")
        ));
        contacts.add(new Contact("Scott", "Johnson", "555-9834", "424 Oak Dr",
                MonthDay.of(Month.NOVEMBER, 17),
                Instant.parse("2013-04-04T19:45:01Z")
        ));
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String language = req.getParameter("language");
        if ("french".equalsIgnoreCase(language)) {
            Config.set(req, Config.FMT_LOCALE, Locale.FRANCE);
        }
        if (req.getParameter("empty") != null) {
            req.setAttribute("contacts", Collections.<Contact>emptySet());
        } else {
            req.setAttribute("contacts", contacts);
        }
        req.getRequestDispatcher("/WEB-INF/jsp/view/list.jsp").forward(req, resp);
    }
}

pj4w/ch07/AddressBook/web/WEB-INF/jsp/view/list.jsp
<%--@elvariable id="contacts" type="java.util.SortedSet"--%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html>
<head>
    <title><fmt:message key="title.browser" /></title>
</head>
<body>

<h2><fmt:message key="title.page" /></h2>

<c:choose>
    <c:when test="${fn:length(contacts) == 0}">
        <i><fmt:message key="message.noContacts" /></i>
    </c:when>
    <c:otherwise>
        <c:forEach items="${contacts}" var="contact">
            <b>
                <c:out value="${contact.lastName}, ${contact.firstName}"/>
            </b><br/>
            <c:out value="${contact.address}"/><br/>
            <c:out value="${contact.phoneNumber}"/><br/>
            <c:if test="${contact.birthDay != null}">
                <fmt:message key="label.birthday" />:
                ${contact.birthDay.month.getDisplayName(
                    'FULL', pageContext.response.locale)
                }&nbsp;${contact.birthDay.dayOfMonth}<br/>
            </c:if>
            <fmt:message key="label.creationDate" />:
            <fmt:formatDate value="${contact.oldDateCreated}" type="both"
                            dateStyle="long" timeStyle="long"/>
            <br/><br/>
        </c:forEach>
    </c:otherwise>
</c:choose>
</body>
</html>