pj4w/CustomerSupport/src/main/java/com/wrox/csupport/model/Ticket.java
package com.wrox.csupport.model;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;

public class Ticket {
    private String customerName;
    private String subject;
    private String body;
    private OffsetDateTime dateCreated;
    private Map<String, Attachment> attachments = new LinkedHashMap<>();

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Attachment getAttachment(String name) {
        return attachments.get(name);
    }

    public Collection<Attachment> getAttachments() {
        return attachments.values();
    }

    public void addAttachment(Attachment attachment) {
        attachments.put(attachment.getName(), attachment);
    }

    public int getNumberOfAttachments() {
        return attachments.size();
    }

    public OffsetDateTime getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(OffsetDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }
}

pj4w/CustomerSupport/src/main/java/com/wrox/csupport/servlets/LoginServlet.java
package com.wrox.csupport.servlets;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.util.Hashtable;
import java.util.Map;

@WebServlet(
        name = "loginServlet",
        urlPatterns = {"/login"}
)
public class LoginServlet extends HttpServlet {
    private static final Map<String, String> userDatabase = new Hashtable<>();
    static {
        userDatabase.put("Nick", "ni");
        userDatabase.put("Sarah", "sa");
        userDatabase.put("Mike", "mi");
        userDatabase.put("John", "jo");
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        HttpSession session = req.getSession();
        if (req.getParameter("logout") != null) {
            session.invalidate();
            resp.sendRedirect("login");
            return;
        }
        else if (session.getAttribute("username") != null) {
            resp.sendRedirect("tickets");
            return;
        }

        req.setAttribute("loginFailed", false);
        req.getRequestDispatcher("/WEB-INF/jsp/view/login.jsp")
                .forward(req, resp);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        HttpSession session = req.getSession();
        if (session.getAttribute("username") != null) {
            resp.sendRedirect("tickets");
            return;
        }

        String username = req.getParameter("username");
        String password = req.getParameter("password");
        if (username == null || password == null
                || !userDatabase.containsKey(username)
                || !password.equals(userDatabase.get(username))) {
            req.setAttribute("loginFailed", true);
            req.getRequestDispatcher("/WEB-INF/jsp/view/login.jsp")
                    .forward(req, resp);
        } else {
            session.setAttribute("username", username);
            req.changeSessionId();
            resp.sendRedirect("tickets");
        }
    }
}

pj4w/CustomerSupport/src/main/java/com/wrox/csupport/servlets/TicketServlet.java
package com.wrox.csupport.servlets;

import com.wrox.csupport.model.Attachment;
import com.wrox.csupport.model.Ticket;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Part;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.Map;

@WebServlet(
        name = "ticketServlet",
        urlPatterns = {"/tickets"},
        loadOnStartup = 1
)
@MultipartConfig(
        fileSizeThreshold = 5_242_880, //5MB
        maxFileSize = 20_971_520L, //20MB
        maxRequestSize = 41_943_040L //40MB
)
public class TicketServlet extends HttpServlet {
    private volatile int TICKET_ID_SEQUENCE = 1;

    private Map<Integer, Ticket> ticketDatabase = new LinkedHashMap<>();

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String action = req.getParameter("action");
        if (action == null) {
            action = "list";
        }
        switch (action) {
            case "create":
                showTicketForm(req, resp);
                break;
            case "view":
                viewTicket(req, resp);
                break;
            case "download":
                downloadAttachment(req, resp);
                break;
            case "list":
            default:
                listTickets(req, resp);
                break;
        }
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String action = req.getParameter("action");
        if (action == null) {
            action = "list";
        }
        switch (action) {
            case "create":
                createTicket(req, resp);
                break;
            case "list":
            default:
                resp.sendRedirect("tickets");
                break;
        }
    }

    /**
     * Forwards to JSP page containing form for entering ticket info. The form sends POST to the same servlet.
     */
    private void showTicketForm(HttpServletRequest req, HttpServletResponse resp) throws IOException, ServletException {
        req.getRequestDispatcher("/WEB-INF/jsp/view/ticketForm.jsp")
                .forward(req, resp);
    }

    /**
     * Creates ticket using info from POST request and adds the ticket to the database.
     * @param req request used for getting parameters
     * @param resp response used for redirecting to view page of the added ticket
     */
    private void createTicket(HttpServletRequest req, HttpServletResponse resp) throws IOException, ServletException {
        Ticket ticket = new Ticket();
        ticket.setCustomerName((String)req.getSession().getAttribute("username"));
        ticket.setSubject(req.getParameter("subject"));
        ticket.setBody(req.getParameter("body"));
        ticket.setDateCreated(OffsetDateTime.now());

        Part filePart = req.getPart("file1");
        if (filePart != null) {
            Attachment attachment = processAttachment(filePart);
            if (attachment != null) {
                ticket.addAttachment(attachment);
            }
        }

        int id;
        synchronized (this) {
            id = TICKET_ID_SEQUENCE++;
            ticketDatabase.put(id, ticket);
        }

        resp.sendRedirect("tickets?action=view&ticketId=" + id);
    }

    /**
     * Converts the specified <code>Part</code> object to <code>Attachment</code> object.
     * @param filePart part of multipart request which represents the attachment file
     * @return attachment object containing bytes of attached file
     * @throws IOException if an input exception occurs when getting bytes from file part
     */
    private Attachment processAttachment(Part filePart) throws IOException {
        InputStream stream = filePart.getInputStream();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        int numberOfBytes;
        final byte[] byteArray = new byte[1024];
        while((numberOfBytes = stream.read(byteArray)) != -1) {
            outputStream.write(byteArray, 0, numberOfBytes);
        }

        Attachment attachment = new Attachment();
        attachment.setName(filePart.getSubmittedFileName());
        attachment.setContents(outputStream.toByteArray());

        return attachment;
    }

    private void viewTicket(HttpServletRequest req, HttpServletResponse resp) throws IOException, ServletException {
        String idString = req.getParameter("ticketId");
        Ticket ticket = getTicket(idString, resp);
        if (ticket == null) {
            return;
        }

        req.setAttribute("ticketId", idString);
        req.setAttribute("ticket", ticket);

        req.getRequestDispatcher("/WEB-INF/jsp/view/viewTicket.jsp")
                .forward(req, resp);
    }

    private void downloadAttachment(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        String idString = req.getParameter("ticketId");
        Ticket ticket = getTicket(idString, resp);
        if (ticket == null) {
            return;
        }

        String redirectLocation = "ticket?action=view&ticketId=" + idString;
        String name = req.getParameter("attachment");
        if (name == null) {
            resp.sendRedirect(redirectLocation);
            return;
        }

        Attachment attachment = ticket.getAttachment(name);
        if (attachment == null) {
            resp.sendRedirect(redirectLocation);
            return;
        }

        // The Content-Disposition header forces the browser to ask the client to save or download the file
        // instead of just opening the file inline in the browser.
        resp.setHeader("Content-Disposition", "attachment; filename=" + attachment.getName());
        // The binary content type keeps the data from having some kind of character encoding applied to it.
        resp.setContentType("application/octet-stream");

        ServletOutputStream stream = resp.getOutputStream();
        stream.write(attachment.getContents());
    }

    /**
     * Gets ticket from database by specified id string.
     * @param idString id string
     * @param resp response used for redirect if id not present, ticket not found or exception thrown
     * @return ticket object from the database
     */
    private Ticket getTicket(String idString, HttpServletResponse resp) throws IOException {
        if (idString == null || idString.isEmpty()) {
            resp.sendRedirect("tickets");
            return null;
        }

        try {
            Ticket ticket = ticketDatabase.get(Integer.parseInt(idString));
            if (ticket == null) {
                resp.sendRedirect("tickets");
                return null;
            }
            return ticket;
        } catch(Exception e) {
            resp.sendRedirect("tickets");
            return null;
        }
    }

    /**
     * Forwards to list of tickets, if database contains any tickets.
     * @param resp response used for appending content
     */
    private void listTickets(HttpServletRequest req, HttpServletResponse resp) throws IOException, ServletException {
        req.setAttribute("ticketDatabase", ticketDatabase);
        req.getRequestDispatcher("/WEB-INF/jsp/view/listTickets.jsp")
                .forward(req, resp);
    }
}

pj4w/CustomerSupport/web/WEB-INF/jsp/view/listTickets.jsp
<%--@elvariable id="ticketDatabase" type="java.util.Map<Integer,com.wrox.csupport.model.Ticket>"--%>
<template:basic htmlTitle="Tickets" bodyTitle="Tickets">

<c:choose>
    <c:when test="${ticketDatabase.size() == 0}">
        <p><i>There are no tickets in the system.</i></p>
    </c:when>
    <c:otherwise>
        <c:forEach items="${ticketDatabase}" var="entry">
            Ticket ${entry.key}:
            <a href="<c:url value="/tickets">
                        <c:param name="action" value="view" />
                        <c:param name="ticketId" value="${entry.key}" />
                    </c:url>">
                <c:out value="${wrox:abbreviate(entry.value.subject, 60)}" />
            </a><br/>
            <c:out value="${entry.value.customerName}" /> created ticket
            <wrox:formatDate value="${entry.value.dateCreated}" type="both"
                             timeStyle="short" dateStyle="medium" /><br/>
        </c:forEach>
    </c:otherwise>
</c:choose>

</template:basic>

pj4w/CustomerSupport/web/WEB-INF/jsp/view/login.jsp
<%--@elvariable id="loginFailed type="java.lang.Boolean"--%>
<template:loggedOut htmlTitle="Log In" bodyTitle="Log In">

<p>You must log in to access the customer support site.</p>

<c:if test="${loginFailed}">
    <p><b>The username or password you entered are not correct.
            Please try again.
    </b></p>
</c:if>

<form method="post" action="<c:url value="/login"/>">
    Username:<br/>
    <input type="text" name="username" /><br/><br/>
    Password:<br/>
    <input type="password" name="password" /><br/><br/>
    <input type="submit" value="Log In" />
</form>
</template:loggedOut>

pj4w/CustomerSupport/web/WEB-INF/jsp/view/sessions.jsp
<%--@elvariable id="timestamp" type="long"--%>
<%--@elvariable id="numberOfSessions" type="java.lang.Integer"--%>
<%--@elvariable id="sessionList" type="java.util.List<javax.servlet.http.HttpSession"--%>
<template:basic htmlTitle="Active Sessions" bodyTitle="Active Sessions">

<p>There are a total of ${numberOfSessions} active sessions in this application.</p>
<ul>
    <c:forEach items="${sessionList}" var="s">
        <li>
            <c:out value="${s.id} - ${s.getAttribute('username')}" />
            <c:if test="${s.id == pageContext.session.id}">&nbsp;(you)</c:if>
            &nbsp;- last active
            ${wrox:timeIntervalToString(timestamp - s.lastAccessedTime)} ago
        </li>
    </c:forEach>
</ul>

</template:basic>

pj4w/CustomerSupport/web/WEB-INF/jsp/view/ticketForm.jsp
<template:basic htmlTitle="Create a Ticket" bodyTitle="Create a Ticket">
    <jsp:attribute name="extraNavigaitionContent">
        <a href="<c:url value="/sessions"/>">Session one more time</a><br/>
    </jsp:attribute>
    <jsp:body>
    <form method="post" action="tickets" enctype="multipart/form-data">
        <input type="hidden" name="action" value="create"/>
        <input type="text" name="subject" placeholder="Subject"><br/><br/>
        <textarea name="body" rows="5" cols="30" placeholder="Body"></textarea><br/><br/>
        <b>Attachment(s)</b><br/>
        <input type="file" name="file1"/><br/><br/>
        <input type="submit" value="Submit"/>
    </form>
    </jsp:body>
</template:basic>

pj4w/CustomerSupport/web/WEB-INF/jsp/view/viewTicket.jsp
<%--@elvariable id="ticketId" type="java.lang.String"--%>
<%--@elvariable id="ticket" type"com.wrox.csupport.model.Ticket"--%>
<template:basic htmlTitle="${ticket.subject}" bodyTitle="Ticket #${ticketId}: ${ticket.subject}">

<i>Customer Name - <c:out value="${ticket.customerName}" /><br/>
Created <wrox:formatDate value="${ticket.dateCreated}" type="both" timeStyle="long" dateStyle="full" /></i><br/><br/>

<c:out value="${ticket.body}" /><br/><br/>
<c:if test="${ticket.numberOfAttachments > 0}">
    Attachment(s):
    <c:forEach items="${ticket.attachments}" var="attachment" varStatus="status">
        <c:if test="${!status.first}">, </c:if>
        <a href="<c:url value="/tickets">
                <c:param name="action" value="download" />
                <c:param name="ticketId" value="${ticketId}" />
                <c:param name="attachment" value="${attachment.name}" />
            </c:url>"><c:out value="${attachment.name}" /></a>
    </c:forEach>
</c:if>

</template:basic>